name: tusk_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  #  untuk cara simpel menggunakan button material
  d_button: ^0.0.10
  #  untuk memerikan info
  d_info: ^0.2.0
  #  untuk membuat inputan
  d_input: ^0.1.3
  #  Untuk pengecekan logging
  d_method: ^0.2.6
  #  Untuk penggunaan self reference
  d_session: ^0.0.2
  #  untuk menghandle image network
  extended_image: ^8.2.0
  #  Untuk set management
  flutter_bloc: ^8.1.3
  #  Untuk pemberian jarak
  gap: ^3.0.1
  #  Untuk mengambil data api
  get: ^4.6.6
  #  Untuk mengcostumize font
  google_fonts: ^6.1.0
  #  Untuk berinteraksi dengan api / melakukan request
  http: ^1.2.0
  #  untuk memilihi image dari gallery
  image_picker: ^1.0.7
  #  Untuk formatting tanggal
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # Mengassign tempat assets dan asset kita
  assets:
    - assets/